
set(esp32_common_defs -DESP_PLATFORM "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DHAVE_CONFIG_H -MMD -DCONFIG_FREERTOS_MAX_TASK_NAME_LEN=16 -DCONFIG_FREERTOS_HZ=1000 -DCONFIG_LOG_DEFAULT_LEVEL=2 -DCONFIG_TCP_OVERSIZE_MSS=y -DCONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ=240 -DCONFIG_BT_ENABLED -DCONFIG_CXX_EXCEPTIONS=1 -DCONFIG_BTDM_CONTROLLER_BLE_MAX_CONN_EFF=3 -DCONFIG_BTDM_CONTROLLER_BR_EDR_MAX_ACL_CONN_EFF=2 -DCONFIG_BTDM_CONTROLLER_BR_EDR_MAX_SYNC_CONN_EFF=0)
set(wroom32_defs ${esp32_common_defs} -c -DF_CPU=240000000L -DARDUINO=10808 -DARDUINO_NodeMCU_32S -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"NodeMCU_32S\"" "-DARDUINO_VARIANT=\"nodemcu-32s\"" -DESP32 -DCORE_DEBUG_LEVEL=0)
set(esp32_compiler_set_c -std=gnu99 -Os -g3 -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -Wpointer-arith -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -Wno-old-style-declaration)
set(esp32_compiler_set_cpp -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti)
    
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")   # remove -rdynamic for C
set(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "") # remove -rdynamic for CXX

set(wroom32_linker_options_set1 "-nostdlib -L${ESP32_PATH}/tools/sdk/lib -L${ESP32_PATH}/tools/sdk/ld -T esp32_out.ld -T esp32.common.ld -T esp32.rom.ld -T esp32.peripherals.ld -T esp32.rom.spiram_incompatible_fns.ld -u ld_include_panic_highint_hdl -u call_user_start_cpu0 -Wl,--gc-sections -Wl,-static -Wl,--undefined=uxTopUsedPriority -u __cxa_guard_dummy -u __cxx_fatal_exception")
set(core_output_folder ${CMAKE_BINARY_DIR}/esp32/core)
set(core_libraries "${core_output_folder}/libwroom32_core_c.a ${core_output_folder}/libwroom32_core_cpp.a")
set(wroom32_linker_options_set2 "-Wl,--start-group ${core_libraries} -lgcc -lopenssl -lbtdm_app -lfatfs -lwps -lcoexist -lwear_levelling -lesp_http_client -lhal -lnewlib -ldriver -lbootloader_support -lpp -lmesh -lsmartconfig -ljsmn -lwpa -lethernet -lphy -lesp_ringbuf -lapp_trace -lconsole -lulp -lwpa_supplicant -lfreertos -lbt -lmicro-ecc -lcxx -lxtensa-debug-module -lmdns -lvfs -lsoc -lcore -lsdmmc -lcoap -ltcpip_adapter -lc_nano -lesp-tls -lrtc -lspi_flash -lwpa2 -lesp32 -lapp_update -lnghttp -lspiffs -lespnow -lnvs_flash -lesp_adc_cal -llog -lsmartconfig_ack -lexpat -lm -lc -lheap -lmbedtls -llwip -lnet80211 -lpthread -ljson -lstdc++ -Wl,--end-group"
)
set(wifi_credentials -DMY_SSID="${SSID}" -DMY_WIFI_PASSWD="${WIFI_PASSWD}")