
set(esp32_ble_sources
    ${ESP32_BLE_SRC_DIR}/BLEUUID.cpp
    ${ESP32_BLE_SRC_DIR}/BLEDevice.cpp
    ${ESP32_BLE_SRC_DIR}/BLEClient.cpp
    ${ESP32_BLE_SRC_DIR}/BLEScan.cpp
    ${ESP32_BLE_SRC_DIR}/FreeRTOS.cpp
    ${ESP32_BLE_SRC_DIR}/BLEAddress.cpp
    ${ESP32_BLE_SRC_DIR}/BLEAdvertisedDevice.cpp
    ${ESP32_BLE_SRC_DIR}/BLERemoteService.cpp
    ${ESP32_BLE_SRC_DIR}/BLERemoteCharacteristic.cpp
    ${ESP32_BLE_SRC_DIR}/BLERemoteDescriptor.cpp
    ${ESP32_BLE_SRC_DIR}/BLEUtils.cpp
    ${ESP32_BLE_SRC_DIR}/GeneralUtils.cpp
    ${ESP32_BLE_SRC_DIR}/BLEServer.cpp
    ${ESP32_BLE_SRC_DIR}/BLEServiceMap.cpp
    ${ESP32_BLE_SRC_DIR}/BLEService.cpp
    ${ESP32_BLE_SRC_DIR}/BLECharacteristicMap.cpp
    ${ESP32_BLE_SRC_DIR}/BLEAdvertising.cpp
    ${ESP32_BLE_SRC_DIR}/BLECharacteristic.cpp
    ${ESP32_BLE_SRC_DIR}/BLEValue.cpp
    ${ESP32_BLE_SRC_DIR}/BLEDescriptorMap.cpp
    ${ESP32_BLE_SRC_DIR}/BLEDescriptor.cpp
    ${ESP32_BLE_SRC_DIR}/BLE2902.cpp
)

set(esp32_wire_sources
    ${ESP32_WIRE_SRC_DIR}/Wire.cpp
)
set(esp32_spi_sources
    ${ESP32_SPI_SRC_DIR}/SPI.cpp
)
set(esp32_fs_sources
    ${ESP32_FS_SRC_DIR}/FS.cpp
    ${ESP32_FS_SRC_DIR}/vfs_api.cpp
)
set(esp32_sd_sources
    ${ESP32_SD_SRC_DIR}/SD.cpp
    ${ESP32_SD_SRC_DIR}/sd_diskio.cpp
    ${ESP32_SD_SRC_DIR}/sd_diskio_crc.c
)
set(esp32_wifi_sources
    ${ESP32_WIFI_SRC_DIR}/WiFi.cpp
    ${ESP32_WIFI_SRC_DIR}/WiFiMulti.cpp
    ${ESP32_WIFI_SRC_DIR}/WiFiSTA.cpp
    ${ESP32_WIFI_SRC_DIR}/WiFiScan.cpp
    ${ESP32_WIFI_SRC_DIR}/WiFiGeneric.cpp
    ${ESP32_WIFI_SRC_DIR}/WiFiServer.cpp
    ${ESP32_WIFI_SRC_DIR}/WiFiClient.cpp
    ${ESP32_WIFI_SRC_DIR}/WiFiAP.cpp
    ${ESP32_WIFI_SRC_DIR}/WiFiUdp.cpp
)
set(esp32_async_udp_sources
    ${ESP32_ASYNC_UDP_SRC_DIR}/AsyncUDP.cpp
)
set(esp32_dns_server_sources
    ${ESP32_DNS_SERVER_SRC_DIR}/DNSServer.cpp
)
set(esp32_mdns_sources
    ${ESP32_MDNS_SRC_DIR}/ESPmDNS.cpp
)